#!/usr/bin/bash

if [ "$1" == "" ]; then
    echo Commit message missing
    exit
fi

git commit -m"${1}" 
version=`git diff @~1..@ -- "$(git rev-parse --show-toplevel)"/package.json | grep '^\+.*version' | sed -s 's/[^0-9\.]//g'`

if [ "$version" != "" ]; then
    git tag -a "v$version" -m "`git log -1 --format=%s`"
    echo "Created a new tag, v$version"
fi
